import type { Metadata } from "next";
import { poppins } from "@/shared/utils/font";
import "@/styles/globals.css"
import Navbar from "@/shared/components/Navbar";
import Footer from "@/shared/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${poppins.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
