import type { Metadata } from "next";
import { poppins } from "@/shared/utils/font";
import { inter } from "@/shared/utils/font";
import "@/styles/globals.css"
import Script from "next/script";
import { ToastProvider } from "@/shared/context/ToastContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable}  antialiased`}
      >
        <Script src="https://cdn.userway.org/widget.js" data-account="nxbubKAjQO" strategy="afterInteractive"/>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
